name: CI/CD for Airflow ETL

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - staging
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dump workspace for debugging
        run: |
          pwd
          ls -R .

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 apache-airflow pandas google-cloud-bigquery
          pip install -r requirements.txt

      - name: Run flake8
        run: flake8 airflow/dags --max-line-length=88

  test:
    runs-on: ubuntu-latest
    needs: lint

    # Configure Airflow to use in-memory DB and a writable HOME
    env:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "sqlite:///:memory:"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_HOME: ${{ github.workspace }}/airflow_home

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dump workspace for debugging
        run: |
          pwd
          ls -R .

      - name: Prepare Airflow Home
        run: mkdir -p $AIRFLOW_HOME

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest apache-airflow
          pip install -r requirements.txt

      - name: Run pytest
        run: python -m pytest tests

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-etl-image .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Push image to Container Registry
        run: |
          docker tag my-etl-image gcr.io/$GCP_PROJECT_ID/my-etl-image:latest
          docker push gcr.io/$GCP_PROJECT_ID/my-etl-image:latest
      # Add your deployment commands here
